---
title: "Реляційні та інші системи"
---

::: {#div1 style="font-family: serif; font-size: 20px;"}
СУБД підтримують один із можливих типів моделей даних: ієрархічну, мережну і реляційну.

Ієрархічна модель організовує дані у вигляді деревоподібної структури. Особливості такої організації полягають у тому, що кілька вузлів нижчого рівня поєднуються з допомогою зв'язків із одним вуз¬лом вищого рівня. Прикладом ієрархічної моделі може бути будь-яка адміністративна структура. У цій моделі виділяють головний об'єкт, через який забезпечується доступ до інших об'єктів системи. Ієрархічна модель призначена для полегшення зберігання та пошуку записів, які можна організувати строго в ієрархічному вигляді.

Мережна модель дає можливість будь-якому об'єкту бути зв'язаним із будь-яким іншим об'єктом. Вона будується за принципом "головний і підлеглий тип одночасно", тобто будь-який об'єкт може бути головним для кількох, і в той самий час може бути підлеглим для інших, Мережні моделі утворюють складні структури, що створює значні труднощі в разі необхідності їх модернізації або розвитку. Для мережної моделі характерний централізований спосіб обробки даних. На одному центральному комп'ютері, що називається сервером, є єдина копія бази даних. Доступ до даних здійснюється з допомогою віддаленого запиту або трансакції.

Реляційна модель являє собою об'єкти та взаємозв'язки між ними у вигляді таблиць.

Суттєвими перевагами реляційної моделі є:

• простота представлення даних, оскільки таблиці явля¬ють собою звичний спосіб формування запитів; • отримання доступу до будь-яких даних будь-якого типу та одночасне використання кількох таблиць бази даних; • високий ступінь незалежності даних, оскільки інтер¬фейс користувача не зв'язаний із деталями фізичної структури пам'яті та стратегією доступу.

У файлах дані зберігаються в прямокутних таблицях такого вигляду:
:::

|         | Поле 1 | Поле 2 | ... | Поле N |
|:-------:|:------:|:------:|:---:|:------:|
| Запис1  |        |        |     |        |
| Запис2  |        |        |     |        |
|   ...   |        |        |     |        |
| Запис N |        |        |     |        |

::: {#div2 style="font-family: serif; font-size: 20px;"}
Рядки цих таблиць називаються *записами,* а стовпчики - *по­лями.* Усі записи поля мають один і той самий тип.СУБД має забезпечити введення до комп'ютера підготовлених даних, тобто імен полів, їх типів і величин.
:::
